src/books/routes.py
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import url_for
from flask import request
from flask import flash
from flask import session
from books import bcrypt
from books import mysql
from books.forms import RegistrationForm
from books.forms import LoginForm
from books.forms import SearchForm
from books.forms import AddBook
from books.forms import AddNote
from functools import wraps
from math import ceil


site = Blueprint('site',__name__,static_folder="static")

def is_logged_in(fn):
    @wraps(fn)
    def wrapper(*args,**kwargs):
        if "user" in session:
            return fn(*args,**kwargs)
        flash("Please login first")
        return redirect(url_for('site.login_page'))
    return wrapper

@site.route('/')
@site.route('/home',methods = ['POST','GET'])
@is_logged_in
def home_page():
    with mysql.connection.cursor() as cursor:
        recommendation_query = """SELECT b.book_id,b.title,a.name FROM books b
                                LEFT JOIN authors a ON b.author_id = a.author_id
                                ORDER BY RAND() LIMIT 3"""
        cursor.execute(recommendation_query)
        result = cursor.fetchall()
    return render_template("home.html",result = result)

@site.route('/register',methods = ['POST','GET'])
def register_page():
    if "user" in session:
        return redirect(url_for('site.home_page'))

    form = RegistrationForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data
        password = form.password.data
        psswd_hash = bcrypt.generate_password_hash(password)
        with mysql.connection.cursor() as cursor:
            email_check = "SELECT email FROM members WHERE email = %s;"
            insert_query = "INSERT INTO members (full_name,email,password) VALUES (%s,%s,%s);"
            cursor.execute(email_check,(email,))
            is_registered = cursor.fetchone()
            if is_registered:
                flash("Email already registered.")
                return render_template("register.html",form=form)
            else:
                cursor.execute(insert_query,(name,email,psswd_hash))
                mysql.connection.commit()

        flash("Registation Successful, please login.",category='success')
        return redirect(url_for('site.login_page'))
    
    if form.errors: 
        for error in form.errors.values():
            flash(error[0])

    return render_template("register.html",form=form)

@site.route('/login',methods = ['POST','GET'])
def login_page():
    if "user" in session:
        return redirect(url_for('site.home_page'))

    form = LoginForm()
    if request.method == "POST":
        email = form.email.data
        password = form.password.data
        with mysql.connection.cursor() as cursor:
            email_check = "SELECT email FROM members WHERE email = %s;"
            password_check = "SELECT password FROM members WHERE email = %s;"
            name = "SELECT member_id,full_name FROM members WHERE email = %s;"
            cursor.execute(email_check,(email,))
            is_email = cursor.fetchone()
            if is_email:
                cursor.execute(password_check,(email,))
                password_check = cursor.fetchone()[0]
                is_password = bcrypt.check_password_hash(password_check,password)
                if is_password:
                    cursor.execute(name,(email,))
                    user = cursor.fetchone()
                    member_id,name = user[0],user[1]
                    session['user'] = name
                    session['id'] = member_id
                    flash(f"Login Successful, Welcome {name}",category='success')
                    return redirect(url_for('site.home_page'))
                flash("Wrong Password, try again")

            else:
                flash("Email Not Found, please register")
                
    return render_template("login.html",form=form)

@site.route('/logout')
def logout():
    session.pop('user',None)
    return redirect(url_for('site.home_page'))

@site.route('/search',methods = ['POST','GET'])
@site.route('/search/<keyword>/page/<int:index>',methods = ['POST','GET'])
@is_logged_in
def search(index = 1, keyword = None):

    def create_result(title,start_page,result_per_page):
        with mysql.connection.cursor() as cursor:
            search_query = """SELECT b.book_id,b.title,b.num_pages,b.publication_date,
                              b.isbn,p.name,a.name,m.full_name
                              FROM books b LEFT JOIN publishers p ON b.publisher_id = p.publisher_id 
                              LEFT JOIN authors a ON b.author_id = a.author_id 
                              LEFT JOIN members m ON b.added_by = m.member_id
                              WHERE b.title LIKE '%%%s%%'""" % title
            cursor.execute(search_query + "LIMIT %s,%s" % (start_page,result_per_page))
            result = cursor.fetchall()
            return result

    search_form = SearchForm()
    add_book = AddBook()
    start_page = (index * 10) - 10
    result_per_page = 10

    if keyword:
        title = keyword
        
        total_query_result = session["total_query"]
        total_pages = session["total_pages"]
            
        result = create_result(title,start_page,result_per_page)

        return render_template('search.html',form=search_form,form_book=add_book,result=result, \
                keyword = title,total_query=total_query_result,total_pages=total_pages, \
                start_page=start_page,current_page=index)

    session.pop('total_query',None)
    session.pop('total_pages',None)
    # below session for passing when add book byself and automatically add to collection,
    # to show difference flashed in collection
    session['add_book_byself'] = False
    return render_template('search.html',form=search_form,form_book=add_book)

@site.route('/searching',methods = ['POST'])
@is_logged_in
def searching():
    title = request.form.get('search')
    index = request.form.get('page',1)
    result_per_page = 10
    
    if title:
        # below to check if there is some input with single quotation or percent, to prevent SQL SYNTAX error 
        title = title.replace("\'","\\'")
        title = title.replace("%","\%")
        # best solution i found so far
        with mysql.connection.cursor() as cursor:
            search_query = "SELECT * FROM books WHERE title LIKE '%%%s%%'" % title
            cursor.execute(search_query)
            total_query_result = cursor.rowcount
            total_pages = ceil(total_query_result/result_per_page)
            if total_query_result == 0:
                flash("No Data Found")
    
        session['search'] = title
        session["total_query"] = total_query_result
        session["total_pages"] = total_pages

    else:
        total_pages = session['total_pages']
        if int(index) > total_pages:
            flash("Out of range pages",category="out_range")
        title = session['search']

    return redirect(url_for('site.search',keyword = title, index = index))

@site.route('/add_book',methods = ["POST"])
def add_book():

    def query_check_or_add(name,table):
        if table == "publishers":
            query_check = "SELECT publisher_id FROM publishers WHERE name = %s;"
            query_add = "INSERT INTO publishers (name) VALUES (%s);"
        else:
            query_check = "SELECT author_id FROM authors WHERE name = %s;"
            query_add = "INSERT INTO authors (name) VALUES (%s);"

        cursor.execute(query_check,(name,))
        id = cursor.fetchone()
        if id:
            return id

        cursor.execute(query_add,(name,))
        mysql.connection.commit()
        cursor.execute(query_check,(name,))
        id = cursor.fetchone()
        return id

    member_id = session['id']
    form = AddBook()
    if form.validate_on_submit():
        title = form.title.data
        num_pages = form.num_pages.data
        publication_date = form.publication_date.data
        isbn = form.isbn.data
        publisher = form.publisher.data
        author = form.author.data

        with mysql.connection.cursor() as cursor:
            title_check = "SELECT book_id FROM books WHERE title = %s;"
            insert_query = """INSERT INTO books (title,num_pages,publication_date,
                            isbn,publisher_id,author_id,added_by) 
                            VALUES (%s,%s,%s,%s,%s,%s,%s);"""
            cursor.execute(title_check,(title,))
            is_registered = cursor.fetchone()
            if is_registered:
                flash("Book already in Database.")
                return redirect(url_for('site.search'))

            publisher_id = query_check_or_add(publisher,'publishers')
            author_id = query_check_or_add(author,'authors')
            cursor.execute(insert_query,(title,num_pages,publication_date,isbn,publisher_id,author_id, \
                           member_id))
            mysql.connection.commit()

            # this run the query again to take book_id and passing to add_collection
            cursor.execute(title_check,(title,))
            is_registered = cursor.fetchone()

        session['add_book_byself'] = True
        return redirect(url_for('site.add_collection',book_id = is_registered ))
    
    if form.errors: 
        for error in form.errors.values():
            flash(error[0])

    return redirect(url_for('site.search'))

@site.route('/add_collection/<int:book_id>',methods = ['GET','POST'])
def add_collection(book_id):

    member_id = session['id']
    with mysql.connection.cursor() as cursor:
        book_id_check = "SELECT book_id FROM collections WHERE member_id = %s and book_id = %s;"
        insert_query = "INSERT INTO collections (member_id,book_id) VALUES (%s,%s);"
        cursor.execute(book_id_check,(member_id,book_id))
        is_registered = cursor.fetchone()
        if is_registered:

src/books/templates/add_note.html
{% extends "base.html" %}

{% block title %}Add Notes{% endblock %}

{% block maincontent %}

<div class="fst-italic">Add Note for</div>
<h4 class="fw-bold">{{ book_title }}</h4>
<form class="h-75 mt-3" method="POST">
    {{ form.hidden_tag() }}
    <div class="row">
        <div class="form-floating mb-3 col-4">
          {{ form.title(class="form-control bg-warning bg-opacity-25 border border-success",
          id="floatingInput",placeholder="Note Title") }}
        <label class="ms-2" for="floatingInput">Note Title</label>
        </div>
        <div class="form-floating mb-3 col-2">
          {{ form.num_page(type="text",class="form-control bg-warning bg-opacity-25 border border-success",
          id="floatingNum",placeholder="Num Page") }}
          <label class="ms-2" for="floatingNum">Num Page, Max ({{ num_pages }})</label>
        </div>
    </div>
    <div class="form-floating col-12 h-75">
      {{ form.description(class="form-control h-100 bg-warning bg-opacity-25 border border-success",
      id="floatingDesc",placeholder="Description") }}
    <label for="floatingDesc">Description</label>
    </div>
    <div class="d-flex justify-content-end mt-2">
      {{ form.submit(class="btn btn-success btn-block btn-md fw-bold") }}
    </div>
</form>

{% endblock %}

src/books/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <!-- <link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen"> -->
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet" media="screen">
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="d-flex flex-column min-vh-100 bg-success bg-opacity-75">
    <!-- Top Navbar -->
    <nav class="navbar navbar-expand-lg bg-warning fixed-top container-fluid shadow border-bottom \
                 border-dark border-1 border-opacity-75">
        <div class="container-fluid">
            <a class="navbar-brand">Book Notes Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" \
                data-bs-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active text-black link-info" aria-current="page"
                            href="{{ url_for('site.home_page') }}">Home</a>
                    </li>
                </ul>

                {% if session.get('user') %}

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-black">Hi, {{ session.get('user') }}</a>
                    </li>
                    <li class="nav-item"><a class="nav-link">|</a></li>
                    <li class="nav-item">
                        <a class="nav-link text-black link-secondary" href="{{ url_for('site.logout') }}">
                            Logout
                        </a>
                    </li>
                </ul>

                {% else %}

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-dark link-secondary {{ 'active text-light' 
                           if active == 'register' else 'text-black' }}" \
                            href="{{ url_for('site.register_page') }}">Register</a>
                    </li>
                </ul>

                {% endif %}
            </div>
        </div>
    </nav>
    <!-- End Top Navbar -->

    {% if session.get('user') %}
    <!-- SideBar -->
    <div class="container-fluid mt-5 bg-info">
        <div class="row">
            <div class="col-2 pt-3 text-light bg-success bg-opacity-75" style="min-height: 87vh;">
                <div class="container-fluid" style="width:200px;">
                    <ul class="nav flex-column" style="width: 180px;">
                        <li class="nav-item text-center my-2 rounded-2">
                            <a class="fs-6 btn btn-outline-warning nav-link link-dark \
                               {{ 'active text-dark fw-bold' if active == 'search' else 'text-light' }}"
                                href="{{ url_for('site.search') }}">Search Book Title</a>
                        </li>
                        <li class="nav-item text-center my-2 rounded-2"><a class="fs-6 btn \
                                btn-outline-warning nav-link link-dark {{ 'active text-dark fw-bold' 
                                if active == 'collection' else 'text-light ' }}"
                                href="{{ url_for('site.collection') }}">Collection</a>
                        </li>
                        <li class="nav-item text-center my-2 rounded-2"><a class="fs-6 btn \
                                btn-outline-warning nav-link link-dark {{ 'active text-dark fw-bold' 
                                if active == 'notes' else 'text-light ' }}"
                                href="{{ url_for('site.note_page') }}">Notes</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- End SideBar -->

            <!-- Block Content -->
            <div class="col pt-3 bg-light">
                {% block maincontent %}{% endblock %}
            </div>
        </div>
    </div>

    {% else %}

    {% block content %}{% endblock %}

    {% endif %}
    <!-- End Block Content -->

    <script src="{{ url_for('static',filename='js/bootstrap.bundle.js') }}"></script>
</body>
<footer class="mt-auto bg-dark bg-opacity-75 border-top border-1 border-dark border-opacity-75 \
                shadow align-middle"">
    <p class=" text-center text-light">© 2022 Eko Putra Sentosa</p>
</footer>

</html>

src/books/templates/edit_note.html
{% extends "base.html" %}

{% block title %}Edit Notes{% endblock %}

{% block maincontent %}

{% set title = result[0] %}
{% set num_page = result[1] %}

<div class="fst-italic">Edit Note for</div>
<h4 class="fw-bold">{{ title }}</h4>
<form class="h-75 mt-3" method="POST">
    {{ form.hidden_tag() }}
    <div class="row">
        <div class="form-floating mb-3 col-4">
          {{ form.title(class="form-control bg-warning bg-opacity-25 border border-success",
          id="floatingInput",placeholder="Note Title",value=title) }}
        <label class="ms-2" for="floatingInput">Note Title</label>
        </div>
        <div class="form-floating mb-3 col-2">
          {{ form.num_page(type="text",class="form-control bg-warning bg-opacity-25 border border-success",
          id="floatingNum",placeholder="Num Page",value=num_page) }}
          <label class="ms-2" for="floatingNum">Num Page, Max ({{ num_pages }})</label>
        </div>
    </div>
    <div class="form-floating col-12 h-75">
      {{ form.description(class="form-control h-100 bg-warning bg-opacity-25 border border-success",
      id="floatingDesc",placeholder="Description") }}
    <label for="floatingDesc">Description</label>
    </div>
    <div class="d-flex justify-content-end mt-2">
      {{ form.submit(class="btn btn-success btn-block btn-md fw-bold",value="Save Changes") }}
    </div>
</form>

{% endblock %}

src/books/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="container-fluid mt-5">
    <div class="row align-items-center">
      <!-- Welcome Panel -->
      <div class="col-md-7 my-2">
        <p class="text-md-center fs-1 fw-bolder">
          NEVER LOSE YOUR NOTE ANYMORE
        </p>
        <p class="text-md-center fs-1 fw-bolder">
          Always tracking your note in spesific page
        </p>
        <p class="text-center">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio maiores rerum provident aliquid alias sapiente quod asperiores doloremque impedit voluptas quaerat, nam facilis adipisci saepe. Assumenda ea nesciunt labore animi?
        </p>
      </div>
      <!-- End Welcome Panel -->

      <!-- Login Panel -->
      <div class="col-md-5 my-2">
        <div class="card mt-3" style="border-radius: 15px;">
            <div class="card-body p-4">
              <h2 class="text-uppercase text-center mb-4">Login account</h2>

              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category,error in messages %}
                      {% if category == 'success' %}
                        <div class="alert alert-success" role="alert">{{ error }}</div>
                      {% else %}
                        <div class="alert alert-danger" role="alert">{{ error }}</div>
                      {% endif %}
                    {% endfor %}
                  </ul>
                {% endif %}
              {% endwith %}

              <form method="POST"> 
                {{ form.hidden_tag() }}
                <div class="form-outline mb-4">
                  {{ form.email(class="form-control",placeholder="Email Address") }}
                </div>
                <div class="form-outline mb-4">
                  {{ form.password(class="form-control",placeholder="Password") }}
                </div>
                <div class="d-flex justify-content-center mb-4">
                  {{ form.submit(class="btn btn-warning btn-block btn-md fw-bold",placeholder="Login") }}
                </div>
                <div class="text-center">
                    <p class="text-center text-muted mt-3 mb-0">Not a member? 
                        <a href="{{ url_for('site.register_page') }}" class="fw-bold text-body">
                            <u>Register</u>
                        </a>
                    </p>
                </div>
              </form>

            </div>
          </div>
      </div>
      <!-- End Login Panel -->
    </div>
</div>

{% endblock %}

src/books/templates/register.html
{% extends 'base.html' %}
{% set active = 'register' %}

{% block title %}Register{% endblock %}

{% block content %}

<section class="mt-4"> 
  <div class="mask d-flex align-items-center h-100">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card mt-5" style="border-radius: 15px;">
            <div class="card-body p-4">
              <h2 class="text-uppercase text-center mb-4">Create account</h2>

              {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for error in messages %}
                      <div class="alert alert-danger" role="alert">{{ error }}</div>
                    {% endfor %}
                  </ul>
                {% endif %}
              {% endwith %}

              <form method="POST">

                {{ form.hidden_tag() }}

                <div class="form-outline mb-4">
                  {{ form.name(class="form-control form-control-md",placeholder="Full Name") }}
                </div>
                <div class="form-outline mb-4">
                  {{ form.email(class="form-control form-control-md",placeholder="Email Address") }}
                </div>
                <div class="form-outline mb-4">
                  {{ form.password(class="form-control form-control-md",placeholder="Password") }}
                </div>
                <div class="form-outline mb-4">
                  {{ form.repeat_password(class="form-control form-control-md",
                  placeholder="Repeat Your Password") }}
                </div>
                <div class="d-flex justify-content-center">
                  {{ form.submit(class="btn btn-warning btn-block btn-md fw-bold") }}
                </div>

                <p class="text-center text-muted mt-3 mb-0">Have already an account? 
                    <a href="{{ url_for('site.login_page') }}" class="fw-bold text-body">
                        <u>Login here</u>
                    </a>
                </p>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

src/books/templates/search.html
{% extends "base.html" %}
{% set active = 'search' %}
{% set page_active = current_page %}

{% block title %}Search{% endblock %}

{% block maincontent %}

  <div class="row my-3">
    <div class="col-lg-6">
      <div class="container-sm">
        <form method="POST" class="d-flex" role="search" action="{{ url_for('site.searching') }}">
          {{ form.hidden_tag() }}
          {{ form.search(class="form-control me-2",placeholder="Search Book Title",
          value=keyword if keyword else "") }}
          {{ form.submit(class="btn btn-outline-success",placeholder="Search")}}
        </form>
      </div>
    </div>
  </div>

  {% if result %}
  <table class="table table-success table-hover table-bordered border-primary">
      <thead>
      <tr class="text-center align-middle table-warning border border-2 border-dark border-opacity-75">
        <th scope="col">Title</th>
        <th scope="col" style="width: 90px;">Total Pages</th>
        <th scope="col" style="width:120px;">Action</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      Found {{ total_query }} Result
        {% for book_id,title,num_pages,pub_date,isbn,publisher,author,added_by in result %}
          <tr>
            <td>{{ title }}
              <!-- Collapse for View Detail-->
              <div class="collapse mt-1" id="detail{{ book_id }}">
                <div class="card card-body py-0 bg-secondary bg-opacity-25">
                  <table class="table table-borderless">
                    <tbody>
                      <tr>
                        <td class="fw-bold" style="width:120px;">Total Pages</td>
                        <td>: {{ num_pages }}</td>
                      </tr>
                      <tr>
                        <td class="fw-bold">Published Date</td>
                        <td>: {{ pub_date }}</td>
                      </tr>
                      <tr>
                        <td class="fw-bold">ISBN</td>
                        <td>: {{ isbn }}</td>
                      </tr>
                      <tr>
                        <td class="fw-bold">Publisher</td>
                        <td>: {{ publisher }}</td>
                      </tr>
                      <tr>
                        <td class="fw-bold">Auhor</td>
                        <td>: {{ author }}</td>
                      </tr>
               
                      {% if added_by != "Eko Putra Sentosa" %}
                      <tr>
                          <td class="text-start fw-semibold fst-italic text-primary">Added by user</td>
                          <td class="text-start fw-semibold fst-italic text-primary">: {{ added_by }}</td>
                        </td>
                      </tr>
                    </tbody>
                    {% endif %}
                  </table>
                </div>
              </div>
            </td>
            <td>{{ num_pages }}</td>
            <td class="text-center">
                  <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" 
                  data-bs-target="#confirmation_add{{ book_id }}">Add</button>
                  <button type="button" class="btn btn-secondary btn-sm" data-bs-toggle="collapse" 
                  data-bs-target="#detail{{ book_id }}">Detail</button>
            </td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
  {% endif %}

  {% with message = get_flashed_messages(with_categories=true) %}
    {% if message %}
        {% for category,msg in message %}
          {% if category == 'success' %}
            <div class="alert alert-success text-center fw-bold py-2" role="alert">{{ msg }}</div>
          {% elif category == 'out_range' %}
            <div class="alert alert-warning text-center fw-bold py-2" role="alert">{{ msg }}</div>
          {% else %}
            <div class="alert alert-danger text-center fw-bold py-2" role="alert">{{ msg }}</div>
            <div class="text-center fw-bold" role="alert">Want to add by yourself? 
              <button type="button" class="btn btn-sm btn-success fst-italic" data-bs-toggle="modal" \
                  data-bs-target="#add">
                click here
              </button>
            </div>
          {% endif %}
        {% endfor %}
    {% endif %}
  {% endwith %}

  <!-- Pagination -->
  <ul class="pagination justify-content-center align-items-center row">
    {% if result %}
      <li class="col-auto page-item pe-0">
        <form method="POST" class="inline" action="{{ url_for('site.searching') }}">
          <input type="hidden" name="page" value="{{ page_active - 1 }}">
          <button type="submit" class="btn btn-sm btn-outline-primary \
              {{ 'disabled' if current_page == 1 else '' }}">
            << Prev
          </button>
        </form>
      </li>
      <li class="col-auto page-item">
        <form method="POST" class="inline" action="{{ url_for('site.searching') }}">
            <input type="hidden" name="page" value="{{ page_active + 1 }}">
          <button type="submit" class="btn btn-sm btn-outline-primary \
              {{ 'disabled' if current_page == total_pages else '' }}">
              Next >>
          </button>
        </form>
      </li>
      <li class="col-auto page-item mx-0 px-0">
          Page 
      </li>
      <li class="col-auto page-item">
          <form class="row row-cols-lg-auto g-3 align-items-center" method="POST" \
              action="{{ url_for('site.searching') }}">
            <input type="text" name="page" class="form-control form-control-sm" \
                value="{{ page_active }}" style="width:40px;">
      </li>
      <li class="col-auto page-item mx-0 px-0">
          of {{ total_pages }} Total Pages
      </li>
      <li class="col-auto page-item">
            <button type="submit" class="btn btn-sm btn-primary">Go</button>
          </form>
      </li>
    {% endif %}
  </ul>
  <!-- End Pagination -->
  
  <!-- Modal Section -->

  <!-- Modal for adding new book title -->
  <div class="modal fade" id="add" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title fw-bold">Insert detail book here</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
        </div>
        <div class="modal-body">
          <form method="POST" action="{{ url_for('site.add_book') }}">
            {{ form_book.hidden_tag() }}
            <div class="mb-3 input-group">
              <span class="input-group-text" style="width:125px;">Title</span>
              {{ form_book.title(class="form-control") }}
            </div>
            <div class="mb-3 input-group">
              <span class="input-group-text" style="width:125px;">Total Pages</span>
              {{ form_book.num_pages(class="form-control") }}
            </div>
            <div class="mb-3 input-group">
              <span class="input-group-text" style="width:125px;">Publication Date</span>
              {{ form_book.publication_date(class="form-control") }}
            </div>
            <div class="mb-3 input-group">
              <span class="input-group-text" style="width:125px;">ISBN</span>
              {{ form_book.isbn(class="form-control",placeholder="optional") }}
            </div>
            <div class="mb-3 input-group">
              <span class="input-group-text" style="width:125px;">Publisher</span>
              {{ form_book.publisher(class="form-control") }}
            </div>
            <div class="mb-3 input-group">
              <span class="input-group-text" style="width:125px;">Author</span>
              {{ form_book.author(class="form-control") }}
            </div>
        </div>
        <div class="modal-footer">
          {{ form_book.submit(class="btn btn-success",placeholder="Add Book")}}
          </form>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal for Add Button Confirmation -->
  {% for book_id,title,num_pages,pub_date,isbn,publisher,author,added_by in result %}
  <div class="modal fade" id="confirmation_add{{ book_id }}" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title fw-bold">{{ title }}</h5>
        </div>
        <div class="modal-body fst-italic">
          Please confirm if you want to add this book.
        </div>
        <div class="modal-footer">
          <form action="{{ url_for('site.add_collection',book_id = book_id) }}" method="POST">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <input type="submit" class="btn btn-success" value="Add to Collection" />
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}


{% endblock %}